# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Bloggerschmidt
tagline:             'Frontend Development'
description:         'Hier schreibt Alexander Schmidt, Webentwickler und CSS Guru'
url:                 https://bloggerschmidt.de
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Alexander Schmidt
  url:               https://twitter.com/bloggerschmidt
  email:             alexander.schmidt@edvas.de

# Custom vars
version:             1.0.0
